const dataFromBD = [
    {
        id: 101,
        title: 'Attila Towal War',
        img: 'https://i.postimg.cc/9fHhskVV/attila.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 102,
        title: 'Total War™: ROME II - Emperor Edition',
        img: 'https://i.postimg.cc/Mp0W20HQ/rome2.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements: 'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 103,
        title: 'Total War: ROME REMASTERED',
        img: 'https://i.postimg.cc/15qmM1ZM/rome-Remastered.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 104,
        title: 'Total War: WARHAMMER',
        img: 'https://i.postimg.cc/bvTNb0jh/warhamer.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',
        
    },
    {
        id: 105,
        title: 'Total War: WARHAMMER II',
        img: 'https://i.postimg.cc/jSYsF3xT/warhamer2.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 106,
        title: 'Total War: WARHAMMER III',
        img: 'https://i.postimg.cc/NMjGxygr/warhamer3.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 107,
        title: 'Total War: THREE KINGDOMS',
        img: 'https://i.postimg.cc/LXQ9QHXQ/three-Kings.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 108,
        title: 'Total War: SHOGUN 2',
        img: 'https://i.postimg.cc/mkcb001L/shogun2.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 109,
        title: 'A Total War Saga: TROY',
        img: 'https://i.postimg.cc/44M4zNjm/troy.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 110,
        title: 'Total War: NAPOLEON – Definitive Edition',
        img: 'https://i.postimg.cc/NFWgYpR1/napoleon.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },
    {
        id: 111,
        title: 'Total War: EMPIRE – Definitive Edition',
        img: 'https://i.postimg.cc/6pCQ6JjT/empire.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',

    },

    {
        id: 112,
        title: 'Sea Thieves',
        img: 'https://i.postimg.cc/SRkVLwWq/seathieves.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'aventura',
    },
    {
        id: 113,
        title: 'Grand Theft Auto V',
        img: 'https://i.postimg.cc/prvt3Tc7/gtav.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 114,
        title: 'Cyberpunk 2077',
        img: 'https://i.postimg.cc/PxYj6ZyY/cyberpunk.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'aventura',
    },
    {
        id: 115,
        title: 'Chivalry 2',
        img: 'https://i.postimg.cc/VN3wB4qz/chivalry.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 116,
        title: 'ACE COMBAT™ 7: SKIES UNKNOWN',
        img: 'https://i.postimg.cc/R039H2nP/acecombat.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 117,
        title: 'Call of Duty®: Modern Warfare® II',
        img: 'https://i.postimg.cc/8zzT17kg/call-Of-Duty-MIIW.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 118,
        title: 'Marvel’s Spider-Man Remastered',
        img: 'https://i.postimg.cc/SNryF6hG/Spiderman.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 119,
        title: 'Gunner, HEAT, PC!',
        img: 'https://i.postimg.cc/057kZgXF/Gunner-Heat.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 120,
        title: 'Project Gunship',
        img: 'https://i.postimg.cc/bN8zB6KJ/Project-Gunship.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 121,
        title: 'Gloomwood',
        img: 'https://i.postimg.cc/6pbtTBT2/Gloom-Wood.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 122,
        title: 'Red Dead Redemption 2',
        img: 'https://i.postimg.cc/kGN758tq/Red-Dead-Redemption.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'aventura',
    },
    {
        id: 123,
        title: 'Mount & Blade II: Bannerlord',
        img: 'https://i.postimg.cc/Y0P4rW4X/Banner-Lord.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'estrategia',
    },
    {
        id: 124,
        title: 'Dead by Daylight',
        img: 'https://i.postimg.cc/wvT3DVLf/Deadby-Light.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'multiplayer',
    },
    {
        id: 125,
        title: 'Devil May Cry 5',
        img: 'https://i.postimg.cc/j5g2c7hs/Devil-May-Cry5.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 126,
        title: 'ELDEN RING',
        img: 'https://i.postimg.cc/MKcMsd4g/Elden-Ring.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'accion',
    },
    {
        id: 127,
        title: 'The Elder Scrolls V: Skyrim Special Edition',
        img: 'https://i.postimg.cc/287Xz1Wx/Skyrim.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'aventura',
    },
    {
        id: 128,
        title: 'The Elder Scrolls V: Skyrim Anniversary Upgrade',
        img: 'https://i.postimg.cc/ZKSMt8WR/Skyrim-Aniversary.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'aventura',
    },
    {
        id: 129,
        title: 'The Witcher® 3: Wild Hunt',
        img: 'https://i.postimg.cc/wjLtz39V/The-Witcher3.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'aventura',
    },
    {
        id: 130,
        title: 'theHunter: Call of the Wild™',
        img: 'https://i.postimg.cc/1zS83PtZ/The-Hunter.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'simuladores',
    },
    {
        id: 131,
        title: 'Stray',
        img: 'https://i.postimg.cc/bYVSHK6Q/Stray.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'aventura',
    },
    {
        id: 132,
        title: 'Guild Wars 2',
        img: 'https://i.postimg.cc/xdPck7JN/Guild-Wars2.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'multiplayer',
    },
    {
        id: 133,
        title: 'Rust',
        img: 'https://i.postimg.cc/8ccJgHCJ/Rust.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'supervivencia',
    },
    {
        id: 134,
        title: 'Assetto Corsa',
        img: 'https://i.postimg.cc/CxwXDG0t/Asset-Corsa.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'carreras',
    },
    {
        id: 135,
        title: 'F1® 22',
        img: 'https://i.postimg.cc/xdCZp9c3/F122.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'carreras',
    },
    {
        id: 136,
        title: 'Construction Simulator',
        img: 'https://i.postimg.cc/J4v5LLTq/Construction-Simulator.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'simuladores',
    },
    {
        id: 137,
        title: 'Forza Horizon 4',
        img: 'https://i.postimg.cc/gjvtLJTm/Forz-Horizon4.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'carreras',
    },
    {
        id: 138,
        title: 'Forza Horizon 5',
        img: 'https://i.postimg.cc/85f0DwdF/Forz-Horizon5.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'carreras',
    },
    {
        id: 139,
        title: 'HOT WHEELS UNLEASHED™',
        img: 'https://i.postimg.cc/CKQQW98T/Hot-Wheels.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'carreras',
    },
    {
        id: 140,
        title: 'Need for Speed™ Heat',
        img: 'https://i.postimg.cc/SR0tK8Vg/Need-For-Speed-Heat.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'carreras',
    },
    {
        id: 141,
        title: 'SnowRunner',
        img: 'https://i.postimg.cc/T2m447YF/Snow-Runner.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'simuladores',
    },
    {
        id: 142,
        title: 'OCTOPATH TRAVELER™',
        img: 'https://i.postimg.cc/X7626Bns/octopathtraveler.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'rol',
    },
    {
        id: 143,
        title: 'NieR Replicant™',
        img: 'https://i.postimg.cc/tJW2VpNd/nierreplicant.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'rol',
    },
    {
        id: 144,
        title: 'Atelier Ryza 2: Lost Legends & the Secret Fairy',
        img: 'https://i.postimg.cc/NGHNnkvy/atelier-Ryza2.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'rol',
    },
    {
        id: 145,
        title: 'Atelier Ryza: Ever Darkness & the Secret Hideout',
        img: 'https://i.postimg.cc/k4kT4BKX/atelier-Ryza.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'rol',
    },
    {
        id: 146,
        title: 'DRAGON QUEST XI S: Ecos de un pasado perdido',
        img: 'https://i.postimg.cc/wvtWghtG/dragon-Cuest-XI.jpg',
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.Placeat nulla quasi tempore perferendis, debitis alias, excepturi doloribus repellat aut velit ab! Saepe, recusandae vero.Ipsam architecto vitae pariatur a.Quidem.',
        price: 100,
        stock: 10,
        requirements:'lorem ipsum dolor sit amet, ipsum dolor sit amet, ipsum dolor sit amet, ipsum',
        category: 'rol',
    },
]

export default dataFromBD;